[cfst]
path = "D:\\Dev\\cfst_windows_amd64\\cfst.exe"
input_file = "D:\\Dev\\cfst_windows_amd64\\ip.txt"
test_url = "https://jhb.ovh"

[scan]
regions = ["HKG"]
delay_limit_ms = 500
disable_download = true
download_speed_min_mbps = 2.0
download_count = 20
download_duration_seconds = 3
console_rows = 20
top_per_region = 10
default_port = 443

[output]
csv_dir = "artifacts"
preferred_ip_file = "cloudflare_ips.txt"
name_template = "{region}-{latency_ms}ms"

[[manual_preferred]]
address = "www.visa.com.sg"
port = 8443

[[manual_preferred]]
address = "usa.visa.com"
port = 443

[[manual_preferred]]
address = "myanmar.visa.com"
port = 8443

[[manual_preferred]]
address = "www.visa.com.tw"
port = 2053

[[manual_preferred]]
address = "www.visaeurope.ch"
port = 2083

[[manual_preferred]]
address = "www.visa.com.br"
port = 2087

[[manual_preferred]]
address = "www.visasoutheasteurope.com"
port = 2096
